### ISSUE TITLE
Setting babelrc to true isn't picking up .babelrc

### ISSUE THREAD

**Issue by bbohen** [kentcdodds/babel-plugin-tester#1]
I'm having an issue when doing:

```javascript
babelOptions: {
    // doesn't work
    babelrc: true
},
```
This results in an unexpected token error as my test is attempting to parse code that requires multiple babel presets to parse (its a react component). This can easily be fixed by supplying the presets directly in the test config, or by adding the extends option like so:

```javascript
babelOptions: {
    // this works
    presets: ["es2015", "stage-0", "react"],
    // this works too
    extends: path.resolve(__dirname, '..', '.babelrc'),
},
```

I'm wondering if I'm missing something here in regards to preferred approach when using a .babelrc? Looking through the code I don't see any logic around the `babelrc` boolean so I am unsure as to the desired experience here.

I would be happy to PR a fix if this indeed a bug, or update the documentation if I'm just missing something here. Thanks for this tool, it's super useful 👍

**Comment by kentcdodds** [comment]
> Thanks for this tool, it's super useful 👍

I'm glad you think so!

> Looking through the code I don't see any logic around the babelrc boolean so I am unsure as to the desired experience here.

Correct, this just gets forward to [`babel.transform`](https://github.com/kentcdodds/babel-plugin-tester/blob/eb60549ebfe9a520f3fe3ca6852d50ab84464831/src/index.js#L66). So I'm unsure of what's going on here. If you want to add a console.log to make sure it's forwarding properly that'd be cool..... oh wait!

I just realized what's going on. I'm pretty sure that babel needs to know the filename to be able to resolve the babelrc. So we need to provide the `filename` as well. I'm unsure whether we could accomplish that from our perspective inside the tool, you may just have to do:

```javascript
babelOptions: {
  babelrc: true,
  filename: __filename,
}
```

I think that should work. If it does, could you add a note in the documentation about this? Probably a pretty common error...

Actually, it may be a good idea to add an `invariant` if you specify `babelrc: true` and don't specify a `filename`. Could you [Make a Pull Request](http://makeapullrequest.com) for that?

**Comment by bbohen** [comment]
Thanks for the response and absolutely! I'll get on that tonight.

**Comment by kentcdodds** [comment]
I'm actually going to add a `filepath` property in part to support changes I'm making [here](https://github.com/kentcdodds/babel-plugin-tester/issues/4). That'll have an impact here. The `filepath` in the `babelOptions` will default to the `filepath` provided for every test. I'll hopefully have this done soon. I'll let you know.

**Comment by bbohen** [comment]
Sounds good, if the .babelrc relative to that `filepath` can be resolved into a `filename` for babel that would fix this issue. Throwing an `invariant` could still be an option but there might need to be a bit more logic involved as the existence of `presets` or `plugins` would make a .babelrc unnecessary even if the user has specified `babelrc: true`.

**Comment by kentcdodds** [comment]
Let's see how the dust settles as @thejameskyle and I are both actively working on this package right now.

**Comment by kentcdodds** [comment]
Quick question if you're around...

```javascript
pluginTester({
  filename: __filename,
  tests: [
    {
      filename: '/some/path',
      // ...etc
    },
    {
      // should the filename here be derived from the filename of the root-level config?
      // or should it just be undefined as it currently is?
      code: 'blah',
    }
  ]
})
```

**Comment by kentcdodds** [comment]
Note that if we _do_ assume the filename is based on the root-level config, then you could unset that by doing: `filename: undefined` for any of the tests. I think this is the least surprising API so that's what I'm going to go with unless I hear from you :)

**Comment by bbohen** [comment]
I think that will work fine, if it helps at all [here](https://github.com/bbohen/babel-plugin-component-identification/blob/master/__tests__/index.js) is how I ended up using it.

**Comment by kentcdodds** [comment]
I decided that doing all that `filename` business was adding too much complexity and opted for the simpler solution. I added an [example](https://github.com/kentcdodds/babel-plugin-tester/blob/master/other/EXAMPLES.md#working-with-other-plugins) for it which I hope is helpful!
