### ISSUE TITLE
Only/Skip

### ISSUE THREAD

**Issue by thejameskyle** [kentcdodds/babel-plugin-tester#3]
It'd be nice to be able to configure `test.only` or `test.skip`:

```js
{
  title: 'not working yet',
  ...
  skip: true,
},
```

```js
{
  title: 'currently focused on',
  ...
  only: true,
},
```

**Comment by kentcdodds** [comment]
I forgot to document it, but it's available with `modifier: 'only'` though less intuitive than what you suggest. So I'd be good to change. Wouldn't need a breaking change either because it's not documented anyway 😀

**Comment by kentcdodds** [comment]
`modifier` has been dropped in favor of [`only`](https://github.com/kentcdodds/babel-plugin-tester#only) and [`skip`](https://github.com/kentcdodds/babel-plugin-tester#skip)
